server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
 
security:
    oauth2:
        resource:
            token-info-uri: http://localhost:8060/oauth/check_token
        client:
            client-id: client_1
            client-secret: 123456