server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
zuul:
  routes:
    sensitiveHeaders: Cookie,Set-Cookie
    department:
      path: /department/**
      serviceId: department-service
    employee:
      path: /employee/**
      serviceId: employee-service
    organization:
      path: /organization/**
      serviceId: organization-service
    oauth:
        sensitive-headers: 
        path: /oauth/**
        serviceId: oauth-service
        stripPrefix: false
        
security:
    oauth2:
        resource:
            token-info-uri: http://localhost:8060/oauth/check_token
        client:
            client-id: client_1
            client-secret: 123456
      
