node {
  withMaven() {
    stage('Checkout') {
      git url: 'https://github.com/haifengchen/springcloudsample.git', credentialsId: 'haifeng-github', branch: 'master'
    }
    stage('Build') {
      dir('config-service') {
        sh 'mvn clean install'
        def pom = readMavenPom file:'pom.xml'
        print pom.version
        env.version = pom.version
        currentBuild.description = "Release: ${env.version}"
      }
    }
    stage('Image') {
      dir ('config-service') {
        docker.withRegistry('https://localhost:8081') {
          def app = docker.build "haifeng/config-service:${env.version}"
          app.push()
        }
      }
    }
  }
}